problem1: problem1.cpp
		g++ -o problem1 -Wall problem1.cpp

problem2: problem2.cpp
		g++ -o problem2 -Wall problem2.cpp

problem4: problem4.cpp
		g++ -o problem4 -Wall problem4.cpp

problem5: problem5.cpp
		g++ -o problem5 -Wall problem5.cpp

problem6: problem6.cpp
		g++ -o problem6 -Wall problem6.cpp
