problem1: problem1.cpp
		g++ -o problem1 -Wall problem1.cpp

problem2: problem2.cpp
		g++ -o problem2 -Wall problem2.cpp

problem2-c: problem2-c.cpp
		g++ -o problem2-c -Wall problem2-c.cpp

all: problem1 problem2 problem2-c
		./problem1 problem2 problem2-c
